#!/bin/sh

# PROVIDE: mosdns_controller
# REQUIRE: mosdns
# KEYWORD: shutdown

. /etc/rc.subr

name="mosdns_controller"
rcvar="mosdns_controller_enable"

load_rc_config $name

: ${mosdns_controller_enable:="NO"}
: ${mosdns_controller_listen:=":5380"}
: ${mosdns_controller_config:="/usr/local/etc/mosdns/config.yaml"}
: ${mosdns_controller_settings:="/usr/local/etc/mosdns/controller_settings.json"}
: ${mosdns_controller_ruledir:="/usr/local/etc/mosdns/rule"}
: ${mosdns_controller_logfile:="/var/log/mosdns-controller.log"}
: ${mosdns_controller_pidfile:="/var/run/mosdns-controller.pid"}

pidfile="${mosdns_controller_pidfile}"
command="/usr/sbin/daemon"
procname="/usr/local/bin/mosdns-controller"
command_args="-p ${pidfile} -o ${mosdns_controller_logfile} -t ${name} ${procname} -listen ${mosdns_controller_listen} -config ${mosdns_controller_config} -settings ${mosdns_controller_settings} -rule-dir ${mosdns_controller_ruledir}"

start_precmd="mosdns_controller_prestart"

mosdns_controller_prestart()
{
    mkdir -p /var/log /var/run /usr/local/etc/mosdns "${mosdns_controller_ruledir}"
    touch "${mosdns_controller_logfile}"
}

run_rc_command "$1"
