#!/bin/sh

# PROVIDE: xray_controller
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="xray_controller"
rcvar="xray_controller_enable"

load_rc_config $name

: ${xray_controller_enable:="NO"}
: ${xray_controller_listen:=":5384"}
: ${xray_controller_confdir:="/usr/local/etc/xray-core"}
: ${xray_controller_data:="/usr/local/etc/xray-core/controller_data.json"}
: ${xray_controller_logfile:="/var/log/xray-controller.log"}
: ${xray_controller_pidfile:="/var/run/xray-controller.pid"}

pidfile="${xray_controller_pidfile}"
command="/usr/sbin/daemon"
procname="/usr/local/bin/xray-controller"
command_args="-p ${pidfile} -o ${xray_controller_logfile} -t ${name} ${procname} -listen ${xray_controller_listen} -confdir ${xray_controller_confdir} -data ${xray_controller_data}"

start_precmd="xray_controller_prestart"

xray_controller_prestart()
{
    mkdir -p /var/log /var/run "${xray_controller_confdir}"
    [ -f "${xray_controller_data}" ] || [ ! -f "${xray_controller_data}.sample" ] || cp "${xray_controller_data}.sample" "${xray_controller_data}"
    touch "${xray_controller_logfile}"
}

run_rc_command "$1"

