PLUGIN_NAME=        mosdns
PLUGIN_VERSION=     1.0.0
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     MosDNS-X Dynamic Routing Engine with pf-aliasd & Controller UI
PLUGIN_MAINTAINER=  admin@opn-box.local
PLUGIN_DEPENDS=     pf-aliasd mosdns

.include "../../Mk/plugins.mk"
