PLUGIN_NAME=        mosdns
PLUGIN_VERSION=     2026.09.24
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     MosDNS-X Dynamic Routing Engine with pf-aliasd & Controller UI
PLUGIN_MAINTAINER=  admin@opn-box.local
PLUGIN_DEPENDS=     pf-aliasd mosdns

.include "../../Mk/plugins.mk"
