[start]
command:/usr/local/etc/rc.d/mosdns start && /usr/local/etc/rc.d/pf_aliasd start
parameters:
type:script
message:starting MosDNS and pf-aliasd services

[stop]
command:/usr/local/etc/rc.d/mosdns stop && /usr/local/etc/rc.d/pf_aliasd stop
parameters:
type:script
message:stopping MosDNS and pf-aliasd services

[restart]
command:/usr/local/etc/rc.d/mosdns restart && /usr/local/etc/rc.d/pf_aliasd restart
parameters:
type:script
message:restarting MosDNS and pf-aliasd services

[status]
command:/usr/local/etc/rc.d/mosdns status && /usr/local/etc/rc.d/pf_aliasd status
parameters:
type:script_output
message:checking MosDNS and pf-aliasd status

[tun2socks.start]
command:/usr/local/etc/rc.d/hev_socks5_tunnel start && /usr/local/etc/rc.d/hev_controller start
parameters:
type:script
message:starting hev-socks5-tunnel and controller

[tun2socks.stop]
command:/usr/local/etc/rc.d/hev_socks5_tunnel stop && /usr/local/etc/rc.d/hev_controller stop
parameters:
type:script
message:stopping hev-socks5-tunnel and controller

[tun2socks.restart]
command:/usr/local/etc/rc.d/hev_socks5_tunnel restart && /usr/local/etc/rc.d/hev_controller restart
parameters:
type:script
message:restarting hev-socks5-tunnel and controller

[tun2socks.status]
command:/usr/local/etc/rc.d/hev_socks5_tunnel status && /usr/local/etc/rc.d/hev_controller status
parameters:
type:script_output
message:checking hev-socks5-tunnel and controller status
