PLUGIN_NAME=        xray
PLUGIN_VERSION=     2026.09.24
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     Xray-core 7-layer Sniffing & Routing Engine with Web UI Manager
PLUGIN_MAINTAINER=  admin@opn-box.local
PLUGIN_DEPENDS=     xray-core

.include "../../Mk/plugins.mk"
