PLUGIN_NAME=        netbox
PLUGIN_VERSION=     2026.09.24
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     NetBox Suite - Unified Policy Routing & Dynamic Split Tunneling
PLUGIN_MAINTAINER=  admin@opn-box.local
PLUGIN_DEPENDS=     os-mosdns os-tun2socks os-xray

.include "../../Mk/plugins.mk"
