PLUGIN_NAME=        tun2socks
PLUGIN_VERSION=     2026.09.24
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     Tun2Socks High-Performance Bridge with Web UI Manager
PLUGIN_MAINTAINER=  admin@opn-box.local
PLUGIN_DEPENDS=     hev-socks5-tunnel

.include "../../Mk/plugins.mk"
